server:
  port: ${PORT:8081}
  
logging:
  level: debug

app:
  config:
    property:
      string: String Property Win G
      long: 100
      boolean: true
      random: ${random.long}
      env: Environment Property Win G
      
---
spring:
  profiles: dev

app:
  config:
    property:
      string: DEV - String Property
      long: 200
      boolean: false
      random: ${random.long}
      env: DEV - Environment Property
