server:
  port: ${PORT:8081}

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    AlunoClient#getAllAlunos():
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 5
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 5
      circuitBreaker:
        requestVolumeThreshold: 5

security:
  basic:
    enabled: false
  user:
    password: none
  oauth2:
    resource:
      preferTokenInfo: false
      userInfoUri: http://localhost:9999/users/current

---
spring:
  profiles: docker

security:
  oauth2:
    resource:
      userInfoUri: http://security-server:9999/users/current        
